# Generated by Django 5.2.7 on 2026-10-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('cta_label', models.CharField(default='Shop Now', max_length=50)),
                ('image', models.ImageField(upload_to='promotions/')),
                ('background_color', models.CharField(default='#F5E6C8', help_text="Hex color matching the image's background, e.g. #F5E6C8", max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
