# Generated by Django 5.2.7 on 2026-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
